import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Logo from "../assets/pokemon.webp";
import { Button } from "@mui/material";

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Hands On Graphql App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.homeContainer}>
        <div className={styles.btnContainer}>
          <Image src={Logo} alt="pokemon" width={200} height={70} />
          <Button
            onClick={() => router.push("/pokemon")}
            sx={{
              color: "yellow",
              bgcolor: "teal",
              mt: 2,
              fontSize: 20,
              px: 5,
              outline: "3px solid yellow",
              "&:hover": {
                bgcolor: "rgba(0, 128, 128, 0.5)",
              },
            }}
          >
            Let's Begin
          </Button>
        </div>
      </div>
    </div>
  );
}
